export const A = {
  bg: '#0d0d0d',
  surface: '#1a1a1a',
  elevated: '#222222',
  border: '#2a2a2a',
  divider: '#1f1f1f',
  text: '#ffffff',
  text2: '#9a9a9a',
  text3: '#6b6b6b',
  textMuted: '#4a4a4a',
  positive: '#22c55e',
  negative: '#ef4444',
  accent: '#3b82f6',
  invertBg: '#ffffff',
  invertText: '#0a0a0a',
  fontSans: "'Inter','Helvetica Neue',Helvetica,Arial,sans-serif",
  fontMono: "'JetBrains Mono','Menlo','Monaco',monospace",
}